import {
  SubAvatarImg1,
  SubAvatarImg2,
  SubAvatarImg3,
  SubAvatarImg4,
  SubAvatarImg5,
  SubAvatarImg6,
  SubAvatarImg7,
  ThumbnailDiscord,
  ThumbnailInstagram,
  ThumbnailNetflix,
  ThumbnailSpotify,
  ThumbnailTiktok,
  ThumbnailTwitter,
  ThumbnailYouTube,
} from "@/assets/images";

export const videosData = [
  {
    thumbnail: ThumbnailYouTube,
    duration: "12:07",
    avatar: SubAvatarImg1,
    title: "A compilation of hilarious cat videos",
    fullName: "Cat Lover",
    views: "10k views",
    posted: "2 weeks ago",
  },
  {
    thumbnail: ThumbnailInstagram,
    duration: "01:15",
    avatar: SubAvatarImg2,
    title: "Learn how to cook a delicious meal",
    fullName: "Chef John",
    views: "2.5k views",
    posted: "1 day ago",
  },
  {
    thumbnail: ThumbnailTiktok,
    duration: "45:22",
    title: "Explore the beauty of Paris in this travel vlog",
    fullName: "Jane Doe",
    views: "780 views",
    posted: "3 days ago",
  },
  {
    thumbnail: ThumbnailNetflix,
    duration: "08:31",
    avatar: SubAvatarImg4,
    title: "See the best moments from a recent gaming stream",
    fullName: "Gamer X",
    views: "123k views",
    posted: "1 month ago",
  },
  {
    thumbnail: ThumbnailTwitter,
    duration: "10:02",
    avatar: SubAvatarImg5,
    title: "Follow a makeup tutorial for a perfect look",
    fullName: "Beauty Guru",
    views: "5.4k views",
    posted: "4 hours ago",
  },
  {
    thumbnail: ThumbnailSpotify,
    duration: "21:59",
    avatar: SubAvatarImg6,
    title: "Hear an honest review of a coding bootcamp",
    fullName: "Tech Learner",
    views: "87 views",
    posted: "1 week ago",
  },
  {
    thumbnail: ThumbnailDiscord,
    duration: "03:04",
    avatar: SubAvatarImg7,
    title: "Watch adorable dogs perform amazing tricks",
    fullName: "Doggo Lover",
    views: "3.1k views",
    posted: "6 days ago",
  },
  {
    thumbnail: ThumbnailYouTube,
    duration: "52:11",
    avatar: SubAvatarImg1,
    title: "Learn about the effects of climate change",
    fullName: "Earth Advocate",
    views: "1.2k views",
    posted: "2 months ago",
  },
  {
    thumbnail: ThumbnailInstagram,
    duration: "17:43",
    avatar: SubAvatarImg2,
    title: "Get a beginner-friendly workout routine",
    fullName: "Fitness Coach",
    views: "4.8k views",
    posted: "30 minutes ago",
  },
  {
    thumbnail: ThumbnailTiktok,
    duration: "00:58",
    avatar: SubAvatarImg3,
    title: "Folding clothes made easy with this life hack",
    fullName: "Marie Kondo Fan",
    views: "9.2k views",
    posted: "yesterday",
  },
  {
    thumbnail: ThumbnailNetflix,
    duration: "23:40",
    avatar: SubAvatarImg4,
    title: "In-depth review and analysis of a recent movie",
    fullName: "Film Critic",
    views: "2.7k views",
    posted: "1 hour ago",
  },
  {
    thumbnail: ThumbnailTwitter,
    duration: "04:12",
    avatar: SubAvatarImg5,
    title: "Get creative with DIY home decor ideas",
    fullName: "Crafty Kim",
    views: "15k views",
    posted: "last week",
  },
  {
    thumbnail: ThumbnailSpotify,
    duration: "01:27",
    avatar: SubAvatarImg6,
    title: "Hilarious compilation of funny baby bloopers",
    fullName: "Proud Parent",
    views: "8.1k views",
    posted: "2 days ago",
  },
  {
    thumbnail: ThumbnailDiscord,
    duration: "07:52",
    avatar: SubAvatarImg7,
    title: "Learn tips and tricks for night sky photography",
    fullName: "Stargazer",
    views: "3.4k views",
    posted: "4 days ago",
  },

  {
    thumbnail: ThumbnailYouTube,
    duration: "28:14",
    avatar: SubAvatarImg1,
    title: "Find inner peace with a meditation guide for beginners",
    fullName: "Inner Peace",
    views: "1.9k views",
    posted: "3 weeks ago",
  },
  {
    thumbnail: ThumbnailInstagram,
    duration: "02:01",
    avatar: SubAvatarImg2,
    title: "Make a delicious and healthy smoothie in just minutes",
    fullName: "Healthy Chef",
    views: "11k views",
    posted: "12 hours ago",
  },
  {
    thumbnail: ThumbnailTiktok,
    duration: "05:39",
    avatar: SubAvatarImg3,
    title: "Test your coding skills with a React tutorial challenge",
    fullName: "Dev Master",
    views: "7.2k views",
    posted: "5 days ago",
  },
  {
    thumbnail: ThumbnailNetflix,
    duration: "41:08",
    avatar: SubAvatarImg4,
    title: "Enjoy a live music performance from a talented band",
    fullName: "The Band",
    views: "2.1k views",
    posted: "2 days ago",
  },
  {
    thumbnail: ThumbnailTwitter,
    duration: "00:37",
    avatar: SubAvatarImg5,
    title: "Non-stop cuteness overload with cat meows and purrs",
    fullName: "Cat Whisperer",
    views: "14k views",
    posted: "8 hours ago",
  },
  {
    thumbnail: ThumbnailSpotify,
    duration: "19:22",
    avatar: SubAvatarImg6,
    title: "Explore the history of Rome in this documentary",
    fullName: "History Buff",
    views: "4.5k views",
    posted: "1 month ago",
  },
  {
    thumbnail: ThumbnailDiscord,
    duration: "06:13",
    avatar: SubAvatarImg7,
    title: "Take your first steps towards learning French",
    fullName: "Language Learner",
    views: "8.9k views",
    posted: "4 weeks ago",
  },
  {
    thumbnail: ThumbnailYouTube,
    duration: "35:47",
    title: "Embark on a virtual travel vlog through Tokyo",
    fullName: "Wanderlust",
    views: "1.7k views",
    posted: "3 days ago",
  },
  {
    thumbnail: ThumbnailInstagram,
    duration: "01:56",
    avatar: SubAvatarImg2,
    title: "Watch a compilation of hilarious dog fails",
    fullName: "Dog Lover 2",
    views: "10.3k views",
    posted: "yesterday",
  },
];
