export const subHeaderTags = [
  "All",
  "Music",
  "Javascript",
  "Skills",
  "AI",
  "News",
  "Plan",
  "Trillers",
  "Variety show",
  "Dramedy",
  "Flutter",
  "Sketch comedy",
  "World cup",
  "Highlight films",
  "Industry",
  "Live",
  "Enterpreneurship",
  "Deep House",
  "Baking",
  "Recently uploaded",
  "New to you",
];
